// 等于 import './instance/index'
// import './instance'
// import './lifecircle'
// import './data-binding'
// import './computed-watch'
// import './component/extend'
// import './condition'
// import './component/binding'
import './component/define'
